### ISSUE TITLE
About osticket v1.15

### ISSUE THREAD

**Issue by TuNGO-86** [dhimelick/osticket-plugin-statusautochange#2]
Hi, This plugin support osticket v1.15+ ?

**Comment by dhimelick** [comment]
I haven't tested 1.15+ yet. I'm currently running it in 1.14.6 and originally wrote it for 1.11, so it has survived major updates for awhile. If you're able to test 1.15 and let me know that it works, I can include that in the README.

**Comment by dhimelick** [comment]
I recently upgraded to 1.15, and this plugin continues to work fine as far as I've seen. I updated the README to reflect this.
